# Generated by Django 3.2.13 on 2022-06-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='paragraph3',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='paragraph4',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='paragraph5',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='playlist',
            field=models.CharField(choices=[('00', '00s - 10s'), ('90', '90s'), ('80', '80s'), ('70', '70s'), ('60', '50s - 60s'), ('OT', 'Other'), ('CE', 'Ceremony')], default='CE', max_length=50),
        ),
    ]
