# Generated by Django 3.2.13 on 2022-07-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_testimonial_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='paragraph2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
